/**
 * Products merged from the Product Researcher feeds (/workspace/website/product-feed/<category>/products.json).
 * GENERATED by scripts/ingest_feed.py — do not edit by hand. Source data: src/data/feed-products.json.
 */
import type { Product } from "@/lib/products";

export const feedProducts: (Product & { sub: string })[] = [];
