export type ProductCategory =
  | "Aluminum profiles"
  | "LED strip lights"
  | "Wall washers"
  | "Drivers & control"
  | "Accessories"
  | "Luminaires"
  | "Electrical package";

export type ProductTone = "cool" | "warm" | "amber" | "blue" | "green" | "soft" | "silver" | "violet";

export type Product = {
  id: string;
  name: string;
  category: ProductCategory;
  use: string;
  specs: string[];
  tone: ProductTone;
  featured?: boolean;
  /** Catalog studio plate (or legacy image) illustrating product type */
  image?: string;
};

export const productCategories: ProductCategory[] = [
  "Aluminum profiles",
  "LED strip lights",
  "Wall washers",
  "Drivers & control",
  "Accessories",
  "Luminaires",
  "Electrical package",
];

export const products: Product[] = [
  // ——— Aluminum profiles → profile-recessed, cove-linear, pendant-linear, kitchen-linear ———
  {
    id: "al-recessed-trimless",
    name: "Recessed trimless plaster-in profile",
    category: "Aluminum profiles",
    use: "Flush drywall line for continuous cove and ceiling slots — AL6063-T5 architectural grade.",
    specs: ["AL6063-T5", "Trimless", "Opal / frosted", "End caps", "Heat-sink body"],
    tone: "silver",
    featured: true,
    image: "/products/catalog/cat-al-recessed-trimless.jpg",
  },
  {
    id: "al-recessed-flanged",
    name: "Recessed flanged slot-in profile",
    category: "Aluminum profiles",
    use: "Covers the plaster gap on recessed runs; clean flange for renovation and new-build ceilings.",
    specs: ["AL6063-T5", "Flanged", "Clear / opal diffuser", "Mounting clips", "1–3 m cuts"],
    tone: "silver",
    image: "/products/catalog/cat-al-recessed-flanged.jpg",
  },
  {
    id: "al-slim-surface-u",
    name: "Slim surface-mount U profile",
    category: "Aluminum profiles",
    use: "Silver anodised surface-mount channel for tight corridors, under-cabinet and feature lines.",
    specs: ["Silver anodised", "Slim U", "Opal / clear", "Clips + end caps", "Heat-sink"],
    tone: "silver",
    featured: true,
    image: "/products/catalog/cat-al-slim-surface-u.jpg",
  },
  {
    id: "al-wide-surface",
    name: "Wide surface-mount profile (dual / triple strip)",
    category: "Aluminum profiles",
    use: "Wide extrusion for dual or triple strip layouts — higher output architectural lines.",
    specs: ["Wide body", "Dual / triple", "Lensed 30–60°", "AL6063-T5", "End caps"],
    tone: "warm",
    image: "/products/catalog/cat-al-wide-surface.jpg",
  },
  {
    id: "al-corner-cove",
    name: "Corner / cove internal-angle profile",
    category: "Aluminum profiles",
    use: "Internal-angle extrusion for wall–ceiling coves and soft indirect uplight.",
    specs: ["Internal angle", "Cove", "Frosted diffuser", "Clips", "Cut lengths"],
    tone: "soft",
    image: "/products/catalog/cat-al-corner-cove.jpg",
  },
  {
    id: "al-external-angle",
    name: "External-angle profile",
    category: "Aluminum profiles",
    use: "External corner channel for shelf edges, steps and architectural reveals.",
    specs: ["External angle", "AL6063-T5", "Opal diffuser", "End caps", "Mount clips"],
    tone: "silver",
    image: "/products/catalog/cat-al-external-angle.jpg",
  },
  {
    id: "al-pendant",
    name: "Pendant / suspended linear profile",
    category: "Aluminum profiles",
    use: "Continuous suspended runs for offices, lobbies and retail — joinable linear sections.",
    specs: ["Suspended", "Continuous join", "Opal / lensed", "Suspension kit", "Heat-sink"],
    tone: "cool",
    featured: true,
    image: "/products/catalog/cat-al-pendant.jpg",
  },
  {
    id: "al-inground",
    name: "In-ground walkable profile IP67",
    category: "Aluminum profiles",
    use: "Walkable in-ground channel for plazas, driveways and pathway edge lighting.",
    specs: ["IP67", "Walkable", "Heavy extrude", "Frosted / clear", "Drain-ready"],
    tone: "green",
    image: "/products/catalog/cat-al-inground.jpg",
  },
  {
    id: "al-hermetic",
    name: "Hermetic outdoor profile IP67",
    category: "Aluminum profiles",
    use: "Heavy-duty façade extrusion for 24V outdoor linear — sealed for coastal UAE exposure.",
    specs: ["IP67", "Façade class", "24V ready", "SS hardware", "Opal / clear"],
    tone: "blue",
    image: "/products/catalog/cat-al-hermetic.jpg",
  },
  {
    id: "al-bendable",
    name: "Bendable / curved profile",
    category: "Aluminum profiles",
    use: "Curved architectural runs for arcs and soft radii — min radius ~120 mm class.",
    specs: ["Bendable", "~120 mm R", "AL6063 class", "Opal diffuser", "End caps"],
    tone: "amber",
    image: "/products/catalog/cat-al-bendable.jpg",
  },
  {
    id: "al-mini-furniture",
    name: "Mini furniture / cabinet profile",
    category: "Aluminum profiles",
    use: "Compact extrusion for joinery, wardrobe and display cabinets — discreet linear glow.",
    specs: ["Mini width", "Cabinet", "Frosted", "Clips", "Short cuts"],
    tone: "soft",
    image: "/products/catalog/cat-al-mini-furniture.jpg",
  },
  {
    id: "al-stair-handrail",
    name: "Stair / handrail profile",
    category: "Aluminum profiles",
    use: "Handrail and stair-nosing channel for safe, low-glare circulation lighting.",
    specs: ["Stair / rail", "Low glare", "Opal", "AL6063-T5", "Mount clips"],
    tone: "warm",
    image: "/products/catalog/cat-al-stair-handrail.jpg",
  },
  {
    id: "al-matte-black",
    name: "Matte black powder-coated architectural profile",
    category: "Aluminum profiles",
    use: "Powder-coated matte black finish for dark ceilings and high-contrast interiors.",
    specs: ["Matte black PC", "Architectural", "Opal / clear", "End caps", "Heat-sink"],
    tone: "amber",
    image: "/products/catalog/cat-al-matte-black.jpg",
  },
  {
    id: "al-custom-ral",
    name: "Custom RAL / anodised silver / white",
    category: "Aluminum profiles",
    use: "Cut lengths typically 1–3 m in anodised silver, white or specified RAL — project finish match.",
    specs: ["Custom RAL", "Anodised options", "1–3 m cuts", "Diffuser suite", "Project finish"],
    tone: "silver",
    image: "/products/catalog/cat-al-custom-ral.jpg",
  },
  {
    id: "al-surface-deep",
    name: "Deep surface-mount profile with lensed optic",
    category: "Aluminum profiles",
    use: "Deeper channel for glare control with 30–60° lensed covers on surface runs.",
    specs: ["Deep body", "30–60° lens", "AL6063-T5", "Clips", "End caps"],
    tone: "cool",
    image: "/products/catalog/cat-al-surface-deep.jpg",
  },

  // ——— LED strip lights → led-strip-profile, cove-linear, rgb-ambient, kitchen-linear ———
  {
    id: "led-cob-ip20",
    name: "24V COB IP20 high-CRI 90+",
    category: "LED strip lights",
    use: "Dotless interior tape for villas and retail — continuous line without visible diodes.",
    specs: ["24V", "COB", "IP20", "CRI 90+", "Dotless"],
    tone: "warm",
    featured: true,
    image: "/products/catalog/cat-led-cob-ip20.jpg",
  },
  {
    id: "led-cob-ip67",
    name: "24V COB IP67 silicone",
    category: "LED strip lights",
    use: "Silicone-jacket COB for wet zones, outdoor soffits and sheltered façades.",
    specs: ["24V", "COB", "IP67", "Silicone", "CRI 90+"],
    tone: "green",
    image: "/products/catalog/cat-led-cob-ip67.jpg",
  },
  {
    id: "led-cob-ip68",
    name: "24V COB IP68 fountain / pool-edge class",
    category: "LED strip lights",
    use: "Fully sealed COB for fountain rims, pool edges and water-adjacent features.",
    specs: ["24V", "COB", "IP68", "Water edge", "Sealed"],
    tone: "blue",
    image: "/products/catalog/cat-led-cob-ip67.jpg",
  },
  {
    id: "led-smd-2700",
    name: "24V SMD 2700K warm white",
    category: "LED strip lights",
    use: "Warm residential and hospitality ambient — classic villa evening tone.",
    specs: ["24V", "SMD", "2700K", "Warm white", "Cut pitch"],
    tone: "warm",
    image: "/products/catalog/cat-led-smd-2700.jpg",
  },
  {
    id: "led-smd-3000",
    name: "24V SMD 3000K hospitality",
    category: "LED strip lights",
    use: "Hospitality-grade neutral-warm for lobbies, F&B and guest corridors.",
    specs: ["24V", "SMD", "3000K", "Hospitality", "CRI 90+"],
    tone: "amber",
    featured: true,
    image: "/products/catalog/cat-led-smd-2700.jpg",
  },
  {
    id: "led-smd-4000",
    name: "24V SMD 4000K neutral",
    category: "LED strip lights",
    use: "Neutral white for offices, retail floors and task-adjacent architectural lines.",
    specs: ["24V", "SMD", "4000K", "Neutral", "Cut pitch"],
    tone: "cool",
    image: "/products/catalog/cat-led-smd-in-channel.jpg",
  },
  {
    id: "led-tunable-cct",
    name: "24V tunable CCT 2700–6000K",
    category: "LED strip lights",
    use: "Tunable white for circadian and scene-set interiors — villas and premium offices.",
    specs: ["24V", "CCT 2700–6000K", "Tunable", "Controller ready", "CRI 90+"],
    tone: "soft",
    image: "/products/catalog/cat-led-cct-in-channel.jpg",
  },
  {
    id: "led-rgb",
    name: "24V RGB",
    category: "LED strip lights",
    use: "RGB colour for feature walls, gaming rooms and event spaces.",
    specs: ["24V", "RGB", "Controller", "Cut pitch", "Interior / IP options"],
    tone: "violet",
    image: "/products/catalog/cat-led-rgb.jpg",
  },
  {
    id: "led-rgbw",
    name: "24V RGBW",
    category: "LED strip lights",
    use: "RGB plus dedicated white channel for accurate white and saturated colour.",
    specs: ["24V", "RGBW", "White channel", "DMX / PWM", "Cut pitch"],
    tone: "violet",
    image: "/products/catalog/cat-led-rgb.jpg",
  },
  {
    id: "led-rgb-cct",
    name: "24V RGB+CCT",
    category: "LED strip lights",
    use: "Full colour plus tunable white in one tape — entertainment and multi-scene interiors.",
    specs: ["24V", "RGB+CCT", "Multi-scene", "Controller", "Cut pitch"],
    tone: "violet",
    image: "/products/catalog/cat-led-cct-in-channel.jpg",
  },
  {
    id: "led-12v-short",
    name: "12V short-run interior strip",
    category: "LED strip lights",
    use: "Short interior runs for joinery and niches where 12V gear is preferred.",
    specs: ["12V", "Short run", "Interior", "Cut pitch", "IP20 class"],
    tone: "soft",
    image: "/products/catalog/cat-led-smd-in-channel.jpg",
  },
  {
    id: "led-48v-facade",
    name: "48V long-run façade linear",
    category: "LED strip lights",
    use: "Long-run façade tape with voltage-drop control for extended elevations.",
    specs: ["48V", "Long run", "Façade", "Voltage-drop control", "Outdoor class"],
    tone: "blue",
    image: "/products/catalog/cat-led-high-output.jpg",
  },
  {
    id: "led-neon-flex",
    name: "High-density COB neon-flex silicone IP67",
    category: "LED strip lights",
    use: "Side-bend neon-flex look for signage, curves and outdoor graphic lines.",
    specs: ["COB neon-flex", "IP67", "Silicone", "High density", "Bendable"],
    tone: "amber",
    image: "/products/catalog/cat-led-neon-flex.jpg",
  },
  {
    id: "led-narrow-cob",
    name: "Narrow 5–8 mm COB for tight profiles",
    category: "LED strip lights",
    use: "Ultra-narrow COB for mini furniture and slim architectural channels.",
    specs: ["5–8 mm", "COB", "24V", "Tight profile", "Dotless"],
    tone: "silver",
    image: "/products/catalog/cat-led-narrow-cob.jpg",
  },
  {
    id: "led-high-output",
    name: "High-output 15–20 W/m architectural tape",
    category: "LED strip lights",
    use: "Higher wattage class for wall wash and bright cove where output matters.",
    specs: ["15–20 W/m", "Architectural", "24V preferred", "Heat-sink profile", "CRI 90+"],
    tone: "warm",
    image: "/products/catalog/cat-led-high-output.jpg",
  },
  {
    id: "led-rgbic",
    name: "RGBIC / addressable",
    category: "LED strip lights",
    use: "Pixel-addressable entertainment and gaming-room effects — chase and gradient scenes.",
    specs: ["RGBIC", "Addressable", "Entertainment", "Controller", "Cut pitch"],
    tone: "violet",
    image: "/products/catalog/cat-led-rgb.jpg",
  },
  {
    id: "led-cob-3000-cri",
    name: "24V COB 3000K CRI 95 retail class",
    category: "LED strip lights",
    use: "High-CRI COB for retail and villa display — colour-critical interiors.",
    specs: ["24V", "COB", "3000K", "CRI 95", "Retail / villa"],
    tone: "warm",
    image: "/products/catalog/cat-led-cob-in-channel.jpg",
  },

  // ——— Wall washers → facade-wash, wall-washer-stone, rgb-ambient ———
  {
    id: "ww-500-mono-3000",
    name: "Linear 500 mm IP65 mono 3000K",
    category: "Wall washers",
    use: "Compact mono wall washer for villa façades and short elevation modules.",
    specs: ["500 mm", "IP65", "3000K", "Mono", "Die-cast Al"],
    tone: "warm",
    featured: true,
    image: "/products/catalog/cat-ww-500-mono-3000.jpg",
  },
  {
    id: "ww-1000-mono-4000",
    name: "Linear 1000 mm IP65/67 mono 4000K",
    category: "Wall washers",
    use: "Metre-length mono wash for towers and commercial façades — neutral white.",
    specs: ["1000 mm", "IP65/67", "4000K", "Mono", "SS hardware"],
    tone: "cool",
    image: "/products/catalog/cat-ww-1000-mono-4000.jpg",
  },
  {
    id: "ww-1000-rgbw-dmx",
    name: "Linear 1000 mm RGBW DMX512 IP67",
    category: "Wall washers",
    use: "DMX512 RGBW façade bar for programmable colour elevations.",
    specs: ["1000 mm", "RGBW", "DMX512", "IP67", "Die-cast Al"],
    tone: "violet",
    image: "/products/catalog/cat-ww-1000-rgbw-dmx.jpg",
  },
  {
    id: "ww-rgb-dmx-ip65",
    name: "Linear RGB DMX IP65",
    category: "Wall washers",
    use: "RGB DMX linear for plazas and feature walls with outdoor rating.",
    specs: ["RGB", "DMX", "IP65", "Linear", "Coastal SS"],
    tone: "violet",
    image: "/products/catalog/cat-ww-rgb-dmx-ip65.jpg",
  },
  {
    id: "ww-asymmetric-graze",
    name: "Asymmetric 15×30 / 10×32 graze optic",
    category: "Wall washers",
    use: "Grazing optic for textured stone and cladding — tight vertical wash.",
    specs: ["15×30 / 10×32", "Asymmetric", "Graze", "IP65+", "Die-cast"],
    tone: "amber",
    image: "/products/catalog/cat-ww-asymmetric-graze.jpg",
  },
  {
    id: "ww-narrow-15",
    name: "Narrow 15° accent beam",
    category: "Wall washers",
    use: "Narrow accent for columns, niches and sculptural elements.",
    specs: ["15°", "Accent", "Narrow beam", "IP65", "0–10V / DMX"],
    tone: "cool",
    image: "/products/catalog/cat-ww-narrow-15.jpg",
  },
  {
    id: "ww-30-wash",
    name: "30° wall wash",
    category: "Wall washers",
    use: "Classic 30° wash optic for even façade planes and lobby walls.",
    specs: ["30°", "Wall wash", "Even field", "IP65/67", "Die-cast Al"],
    tone: "warm",
    image: "/products/catalog/cat-ww-30-wash.jpg",
  },
  {
    id: "ww-60-flood",
    name: "Wide 60° flood wash",
    category: "Wall washers",
    use: "Wide flood for broad elevations and open plaza walls.",
    specs: ["60°", "Flood", "Wide field", "IP65", "SS fixings"],
    tone: "soft",
    image: "/products/catalog/cat-ww-60-flood.jpg",
  },
  {
    id: "ww-pixel",
    name: "Pixel-addressable linear bar",
    category: "Wall washers",
    use: "Pixel bar for media façades and sequenced architectural effects.",
    specs: ["Pixel", "Addressable", "Linear bar", "DMX / SPI", "IP65+"],
    tone: "violet",
    image: "/products/catalog/cat-ww-pixel.jpg",
  },
  {
    id: "ww-flexible",
    name: "Flexible wall-washer / curve façade",
    category: "Wall washers",
    use: "Flexible wash module for curved façades and organic elevations.",
    specs: ["Flexible", "Curve façade", "IP65/67", "Mono / RGB options", "Coastal ready"],
    tone: "blue",
    image: "/products/catalog/cat-ww-flexible.jpg",
  },
  {
    id: "ww-ground-recessed",
    name: "Recessed ground-wash IP67",
    category: "Wall washers",
    use: "In-ground wash uplighting façades and landscape walls from grade.",
    specs: ["Recessed", "IP67", "Ground wash", "Die-cast", "Walk-adjacent"],
    tone: "green",
    image: "/products/catalog/cat-ww-ground-recessed.jpg",
  },
  {
    id: "ww-high-power",
    name: "High-power 36–48 W/m façade bar",
    category: "Wall washers",
    use: "High-output façade bar for tall elevations and long throw wash.",
    specs: ["36–48 W/m", "High power", "Façade", "IP67", "DMX / 0–10V"],
    tone: "amber",
    image: "/products/catalog/cat-ww-high-power.jpg",
  },
  {
    id: "ww-compact-column",
    name: "Compact 18–24 W column washer",
    category: "Wall washers",
    use: "Compact washer for columns, pilasters and narrow verticals.",
    specs: ["18–24 W", "Compact", "Column", "IP65", "Narrow optic"],
    tone: "cool",
    image: "/products/catalog/cat-ww-compact-column.jpg",
  },
  {
    id: "ww-fountain-ip68",
    name: "Fountain / water-feature wash IP68 class",
    category: "Wall washers",
    use: "Submersible-class wash for fountains and water features — sealed hardware.",
    specs: ["IP68 class", "Fountain", "Water feature", "SS hardware", "RGB / mono"],
    tone: "blue",
    image: "/products/catalog/cat-ww-fountain-ip68.jpg",
  },
  {
    id: "ww-0-10v-mono",
    name: "0–10V dimmable mono linear wash IP65",
    category: "Wall washers",
    use: "Analogue 0–10V dimming for hospitality façades and controlled night scenes.",
    specs: ["0–10V", "Mono", "IP65", "Dimmable", "Die-cast Al"],
    tone: "warm",
    image: "/products/catalog/cat-ww-0-10v-mono.jpg",
  },

  // ——— Drivers & control / Accessories / Luminaires / Electrical — subtler effect shots ———
  {
    id: "drv-24v-const",
    name: "24V constant-voltage LED driver / PSU",
    category: "Drivers & control",
    use: "Constant-voltage 24V supply for strip and profile systems — preferred for longer runs.",
    specs: ["24V CV", "PSU", "Power injection ready", "Indoor / IP options", "Project sizing"],
    tone: "silver",
    image: "/products/led-strip-profile-01.jpg",
  },
  {
    id: "drv-dmx-decoder",
    name: "DMX decoder / PWM interface",
    category: "Drivers & control",
    use: "DMX512 to PWM decoding for RGB/RGBW strips and linear wash control.",
    specs: ["DMX512", "PWM out", "RGB / RGBW", "Rack / DIN options", "Scene ready"],
    tone: "violet",
    image: "/products/rgb-ambient-05.jpg",
  },
  {
    id: "acc-opal-diffuser",
    name: "Opal diffuser covers",
    category: "Accessories",
    use: "Opal, frosted, clear and lensed (30–60°) covers for architectural profiles.",
    specs: ["Opal / frosted", "Clear", "30–60° lens", "Profile match", "Cut to length"],
    tone: "soft",
    image: "/products/profile-recessed-03.jpg",
  },
  {
    id: "acc-endcaps-brackets",
    name: "End caps & mounting brackets",
    category: "Accessories",
    use: "End caps, clips and brackets matched to AL6063 profile families.",
    specs: ["End caps", "Clips", "Brackets", "AL match", "Silver / black"],
    tone: "silver",
    image: "/products/profile-recessed-01.jpg",
  },
  {
    id: "lum-emergency-exit",
    name: "Emergency exit luminaires",
    category: "Luminaires",
    use: "Compliant exit and emergency luminaires for towers and public buildings.",
    specs: ["Emergency", "Exit signage", "Maintained options", "Battery pack", "Code-ready"],
    tone: "amber",
    image: "/products/cove-linear-04.jpg",
  },
  {
    id: "lum-downlight",
    name: "LED downlights",
    category: "Luminaires",
    use: "Architectural recessed downlights for villas, offices and retail ceilings.",
    specs: ["Recessed", "CRI 90+", "CCT options", "Cut-out sizes", "Dimmable options"],
    tone: "warm",
    image: "/products/kitchen-linear-02.jpg",
  },
  {
    id: "lum-track-spot",
    name: "Track spots",
    category: "Luminaires",
    use: "Track-mounted accent spots for retail, galleries and feature interiors.",
    specs: ["Track", "Accent", "Beam options", "CRI 90+", "Phase / DALI options"],
    tone: "cool",
    image: "/products/pendant-linear-03.jpg",
  },
  {
    id: "lum-garden-pole",
    name: "Outdoor garden poles",
    category: "Luminaires",
    use: "Landscape bollards and poles for gardens, compounds and promenades.",
    specs: ["IP65+", "Pole / bollard", "Warm / neutral", "Coastal SS", "Ground mount"],
    tone: "green",
    image: "/products/garden-path-01.jpg",
  },
  {
    id: "elec-smdb",
    name: "SMDB / isolators — electrical package",
    category: "Electrical package",
    use: "Sub-main distribution boards and isolators coordinated with lighting packages.",
    specs: ["SMDB", "Isolators", "Main to DB", "Project package", "UAE practice"],
    tone: "silver",
    image: "/products/led-strip-profile-02.jpg",
  },
  {
    id: "drv-12v-compact",
    name: "12V compact PSU for short runs",
    category: "Drivers & control",
    use: "Compact 12V drivers for joinery and short interior strip circuits.",
    specs: ["12V CV", "Compact", "Short run", "Indoor", "Protected"],
    tone: "soft",
    image: "/products/kitchen-linear-01.jpg",
  },
  {
    id: "drv-48v-facade",
    name: "48V façade driver suite",
    category: "Drivers & control",
    use: "Higher-voltage façade drivers for long-run linear with reduced drop.",
    specs: ["48V", "Façade", "Long run", "Outdoor class options", "Injection points"],
    tone: "blue",
    image: "/products/facade-wash-01.jpg",
  },
  {
    id: "acc-connectors",
    name: "Waterproof connectors & injection leads",
    category: "Accessories",
    use: "IP-rated connectors and power-injection leads for outdoor strip and wash systems.",
    specs: ["IP67 connectors", "Injection leads", "24V / 48V", "Outdoor", "Field fit"],
    tone: "green",
    image: "/products/garden-path-04.jpg",
  },
];

export const featuredProducts = products.filter((p) => p.featured).slice(0, 6);

export const productCount = products.length;
