/**
 * Writes product-feed/EXISTING.json (every product on the site) and product-feed/CATEGORIES.json
 * (every valid group / sub-category slug, including hidden empty ones) for the Product Researcher
 * and for scripts/ingest_feed.py duplicate checks.
 *
 *   npm run export-existing        (also runs automatically after `npm run build`)
 *
 * Output folder: $PRODUCT_FEED_DIR, default ../product-feed (i.e. /workspace/website/product-feed).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { allGroups, catalog, groups, VOLTAGE_SUBS } from "../src/lib/catalog";
import { brandOf, voltageOf } from "../src/lib/products";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = resolve(process.env.PRODUCT_FEED_DIR ?? resolve(root, "../product-feed"));
mkdirSync(out, { recursive: true });

const generated_at = new Date().toISOString();
const products = catalog.map((c) => {
  const models = [c.model, ...(c.variants ?? []).map((v) => v.model)].filter((m): m is string => !!m);
  return {
    slug: c.id,
    brand: brandOf(c),
    model: c.model ?? (models.length === 1 ? models[0] : models.length ? models.join(" / ") : null),
    models,
    name: c.name,
    brand_group: c.group.brandGroup,
    category: c.group.slug,
    sub_category: c.sub.slug,
    category_name: `${c.group.name} › ${c.sub.name}`,
    voltage: voltageOf(c) ?? null,
    url: `https://abbaselectricals.com${c.href}`,
  };
});

const byBrandGroup: Record<string, number> = {};
const byBrand: Record<string, number> = {};
for (const p of products) {
  byBrandGroup[p.brand_group] = (byBrandGroup[p.brand_group] ?? 0) + 1;
  byBrand[p.brand] = (byBrand[p.brand] ?? 0) + 1;
}

writeFileSync(
  resolve(out, "EXISTING.json"),
  JSON.stringify(
    {
      note: "GENERATED by `npm run export-existing` (runs after every build). Do not edit. Duplicate = same brand + model (any entry in `models`), or same slug.",
      generated_at,
      total: products.length,
      by_brand_group: byBrandGroup,
      by_brand: byBrand,
      products,
    },
    null,
    2
  ) + "\n"
);

const visible = new Set(groups.flatMap((g) => g.subs.map((s) => `${g.slug}/${s.slug}`)));
writeFileSync(
  resolve(out, "CATEGORIES.json"),
  JSON.stringify(
    {
      note: "GENERATED by `npm run export-existing`. Valid group / sub slugs for feeds. Empty sub-categories are hidden on the site until they have products.",
      generated_at,
      voltage_subs: VOLTAGE_SUBS,
      groups: allGroups.map((g) => ({
        brand_group: g.brandGroup,
        category: g.slug,
        name: g.name,
        sub_categories: g.subs.map((s) => ({
          sub_category: s.slug,
          name: s.name,
          products: catalog.filter((c) => c.group.slug === g.slug && c.sub.slug === s.slug).length,
          visible: visible.has(`${g.slug}/${s.slug}`),
        })),
      })),
    },
    null,
    2
  ) + "\n"
);

console.log(`export-existing: ${products.length} products → ${resolve(out, "EXISTING.json")}`);
console.log(`  by brand_group: ${JSON.stringify(byBrandGroup)}`);
